[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "erc721a/=lib/ERC721A/",
]

[rpc_endpoints]
base_sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }


